services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    volumes:
      - /umbrel/home/Downloads:/music
      - ${APP_DATA_DIR}/data:/config
    ports:
      - "1970:1970"
    restart: unless-stopped
